"""initial schema

Revision ID: 69fc88a18928
Revises: 
Create Date: 2026-06-28 21:09:22.270899
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '69fc88a18928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('dealership_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('dealerships',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealerships'))
    )
    with op.batch_alter_table('dealerships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealerships_name'), ['name'], unique=False)

    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_key'), ['key'], unique=True)

    op.create_table('agent_executions',
    sa.Column('dealership_id', sa.String(length=36), nullable=True),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('evaluated', 'triggered', 'skipped', 'error', name='agentexecutionstatus'), nullable=False),
    sa.Column('decision_should_execute', sa.Boolean(), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('triggered_execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_agent_executions_dealership_id_dealerships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_executions'))
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('customers',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_customers_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('service_bays',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('available', 'occupied', 'maintenance', name='servicebaystatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_service_bays_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_bays'))
    )
    with op.batch_alter_table('service_bays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_bays_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_suppliers_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('technicians',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=128), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_technicians_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technicians'))
    )
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technicians_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('users',
    sa.Column('dealership_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_users_dealership_id_dealerships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workflow_executions',
    sa.Column('dealership_id', sa.String(length=36), nullable=True),
    sa.Column('definition_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting_approval', 'completed', 'failed', 'cancelled', name='workflowstatus'), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by_agent_execution_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_workflow_executions_dealership_id_dealerships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_executions'))
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_definition_key'), ['definition_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_status'), ['status'], unique=False)

    op.create_table('inventory_items',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('unit_cost_minor', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_inventory_items_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_inventory_items_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=False)

    op.create_table('notifications',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', 'in_app', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_notifications_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_notifications_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'confirmed', 'partially_received', 'received', 'cancelled', name='purchaseorderstatus'), nullable=False),
    sa.Column('total_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_purchase_orders_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_number'), ['number'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('vehicles',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('vin', sa.String(length=64), nullable=False),
    sa.Column('registration_no', sa.String(length=32), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('brake_life_pct', sa.Integer(), nullable=False),
    sa.Column('battery_health_pct', sa.Integer(), nullable=False),
    sa.Column('next_service_due', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_vehicles_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_vehicles_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_registration_no'), ['registration_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vin'), ['vin'], unique=True)

    op.create_table('workflow_steps',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting_approval', 'completed', 'failed', 'skipped', name='stepstatus'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name=op.f('fk_workflow_steps_execution_id_workflow_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps'))
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_execution_id'), ['execution_id'], unique=False)

    op.create_table('appointments',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('service_bay_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'scheduled', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_appointments_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_appointments_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_bay_id'], ['service_bays.id'], name=op.f('fk_appointments_service_bay_id_service_bays'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_appointments_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_dealership_id'), ['dealership_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('receipt', 'issue', 'reservation', 'adjustment', 'return_', name='inventorytransactiontype'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_transactions_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_inventory_item_id'), ['inventory_item_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_purchase_order_items_inventory_item_id_inventory_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items'))
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('telematics_events',
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_telematics_events_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telematics_events'))
    )
    with op.batch_alter_table('telematics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telematics_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_telematics_events_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('technician_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'awaiting_parts', 'in_progress', 'completed', 'invoiced', 'cancelled', name='workorderstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('labor_amount_minor', sa.Integer(), nullable=False),
    sa.Column('parts_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_work_orders_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_work_orders_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_work_orders_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_work_orders_technician_id_technicians'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_work_orders_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_work_orders_appointment_id'))
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_number'), ['number'], unique=True)

    op.create_table('invoices',
    sa.Column('dealership_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'partially_paid', 'void', name='invoicestatus'), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_invoices_dealership_id_dealerships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_invoices_work_order_id_work_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('work_order_id', name=op.f('uq_invoices_work_order_id'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_dealership_id'), ['dealership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)

    op.create_table('work_order_items',
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('is_labor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_work_order_items_inventory_item_id_inventory_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_items_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_items'))
    )
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_items_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('payments',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'upi', 'bank_transfer', 'wallet', name='paymentmethod'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_items_work_order_id'))

    op.drop_table('work_order_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_dealership_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_dealership_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('telematics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telematics_events_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_telematics_events_event_type'))

    op.drop_table('telematics_events')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_inventory_item_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_dealership_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_execution_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicles_registration_no'))
        batch_op.drop_index(batch_op.f('ix_vehicles_dealership_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_customer_id'))

    op.drop_table('vehicles')
    op.drop_table('user_roles')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_dealership_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_dealership_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_dealership_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_definition_key'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_dealership_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_dealership_id'))

    op.drop_table('users')
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technicians_dealership_id'))

    op.drop_table('technicians')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_dealership_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('service_bays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_bays_dealership_id'))

    op.drop_table('service_bays')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_dealership_id'))

    op.drop_table('customers')
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_dealership_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_agent_key'))

    op.drop_table('agent_executions')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_key'))

    op.drop_table('roles')
    with op.batch_alter_table('dealerships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealerships_name'))

    op.drop_table('dealerships')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_dealership_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
